param(
  [Parameter(Mandatory)][string]$Rc17Path,
  [Parameter(Mandatory)][string]$Rc18Path,
  [Parameter(Mandatory)][string]$Rc17ValidationPath,
  [Parameter(Mandatory)][string]$ResultPath
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$stage='START'
function Parse-Main([string]$Path){$t=$null;$e=$null;$a=[Management.Automation.Language.Parser]::ParseFile($Path,[ref]$t,[ref]$e);if($e.Count-gt0){throw('ParseFile '+(($e|%{$_.ErrorId+':'+$_.Message})-join' | '))};$a}
function Get-Payload([object]$Ast,[string]$Name){$all=@($Ast.FindAll({param($n)$n-is[Management.Automation.Language.AssignmentStatementAst]-and$n.Left.Extent.Text-eq('$script:'+$Name)},$true));if($all.Count-ne1){throw('Payload count '+$Name+'='+$all.Count)};$r=$all[0].Right;if($r-isnot[Management.Automation.Language.CommandExpressionAst]){throw'payload rhs'};$l=$r.Expression;if($l-isnot[Management.Automation.Language.StringConstantExpressionAst]){throw'payload literal'};[string]$l.Value}
function Get-Fn([object]$Ast,[string]$Name){$f=@($Ast.FindAll({param($n)$n-is[Management.Automation.Language.FunctionDefinitionAst]-and$n.Name-eq$Name},$true));if($f.Count-ne1){throw('Function count '+$Name+'='+$f.Count)};[string]$f[0].Extent.Text}
function FailReceipt([string]$m,[object]$er){try{[ordered]@{schema='miningsniper-rc18-prechat-validation/v1';status='FAIL';stage=$stage;powershell=$PSVersionTable.PSVersion.ToString();platform=[Environment]::OSVersion.Platform.ToString();rc18_sha256=if(Test-Path $Rc18Path){(Get-FileHash $Rc18Path -Algorithm SHA256).Hash.ToLowerInvariant()}else{$null};error_message=$m;script_stack=if($er){$er.ScriptStackTrace}else{$null}}|ConvertTo-Json -Depth 20|Set-Content $ResultPath -Encoding utf8}catch{}}
try{
 $stage='PARSE_IDENTITY';$a17=Parse-Main $Rc17Path;$a18=Parse-Main $Rc18Path;$v17=Get-Content -Raw $Rc17ValidationPath|ConvertFrom-Json;if($v17.status-ne'PASS'){throw'RC17 baseline not PASS'};$src=Get-Content -Raw $Rc18Path;if($src-notmatch'GPU_LANE_R065_RC18'-or$src-notmatch'0\.65\.3-gpu-rc18'){throw'RC18 identity missing'};if($src-match'RC17|rc17'){throw'Stale RC17 identity'}
 $stage='PAYLOAD_PARITY';$names=@('LearningModulePayload','SupervisorPayload','DutyFixturePayload','StopPayload','StatusPayload','ExportPayload');$p17=@{};$p18=@{};$parse=[ordered]@{};$parity=[ordered]@{};foreach($n in $names){$p17[$n]=Get-Payload $a17 $n;$p18[$n]=Get-Payload $a18 $n;$t=$null;$e=$null;[void][Management.Automation.Language.Parser]::ParseInput($p18[$n],[ref]$t,[ref]$e);if($e.Count){throw('payload parse '+$n)};$parse[$n]='PASS';$norm=$p18[$n].Replace('GPU_LANE_R065_RC18','GPU_LANE_R065_RC17').Replace('R065_RC18','R065_RC17').Replace('GPU RC18','GPU RC17').Replace('RC18','RC17').Replace('0.65.3','0.65.2');$parity[$n]=($norm-ceq$p17[$n]);if(-not$parity[$n]){throw('payload drift '+$n)}}
 $stage='NO_CPU_HARD_GATE';foreach($bad in @('Assert-CpuRc6LoopLiveness','CPU_RC6_COEXISTENCE_PRE','CPU_RC6_COEXISTENCE_POST','Probe-XmrigApiAdvisory','PilotA_R063_RC6','R063 RC6 supervisor process is not alive','R063 RC6 CURRENT_RELEASE.json missing')){if($src.Contains($bad)){throw('CPU dependency '+$bad)}}
 $stage='GPU_FLOW';$flow=@('RC14_DUTY_ROOT_CAUSE_FIXTURE','NVIDIA_TELEMETRY_PRECHECK','LOLMINER_PROVENANCE','GENERATED_RUNTIME_GATES','GPU_RUNTIME');$needles=@('Start-MainLearningStage ''RC14_DUTY_ROOT_CAUSE_FIXTURE''','$currentMainLearningStage=''NVIDIA_TELEMETRY_PRECHECK''','$currentMainLearningStage=''LOLMINER_PROVENANCE''','$currentMainLearningStage=''GENERATED_RUNTIME_GATES''','$currentMainLearningStage=''GPU_RUNTIME''');$last=-1;for($j=0;$j-lt$needles.Count;$j++){$i=$src.IndexOf($needles[$j],[StringComparison]::Ordinal);if($i-lt0-or$i-le$last){throw('flow '+$flow[$j])};$last=$i};foreach($x in @('Measure-DutyPhase 0.10','Measure-DutyPhase 0.25','Measure-DutyPhase 0.40','GPU_LIVE','gulf.moneroocean.stream:20128')){if(-not$p18['SupervisorPayload'].Contains($x)){throw('GPU token '+$x)}}
 $stage='MODULE_BOUNDARY';$cmd=@($a18.FindAll({param($n)$n-is[Management.Automation.Language.CommandAst]},$true)|%{$_.GetCommandName()}|?{$_});$priv=@('Get-MsLearningPaths','Get-MsNextRuntimeSeq','New-MsOrderedEvent','Write-MsJournalRecordDurable');foreach($x in $priv){if($x-in$cmd){throw('private call '+$x)}}
 $tmp=Join-Path ([IO.Path]::GetTempPath()) ('MS_RC18_'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Force $tmp|Out-Null
 try{
  $mod=Join-Path $tmp 'MiningSniper.Learning.psm1';Set-Content $mod $p18['LearningModulePayload'] -Encoding utf8;Import-Module $mod -Force;$mi=Get-Module|?{[string]$_.Path-eq[IO.Path]::GetFullPath($mod)}|select -First 1;$exports=@(Get-Command -Module $mi.Name|% Name);foreach($x in @('Sync-MiningSniperLearningBase','Write-MiningSniperLearningEvent','Start-MiningSniperLearningRun','Write-MiningSniperLearningStep','Invoke-MiningSniperLearningStep','Complete-MiningSniperLearningRun','Test-MiningSniperLearningStore')){if($x-notin$exports){throw('missing export '+$x)}};foreach($x in $priv){if($x-in$exports){throw('private export '+$x)}}
  $stage='BOOTSTRAP_FAIL_PERSISTENCE';$br=Join-Path $tmp 'boot';mkdir $br|Out-Null;$bb=Join-Path $br 'MININGSNIPER_LEARNING_BASE.json';[ordered]@{schema='miningsniper-learning-base/v1';learning_revision=40;event_log=@();runtime_event_log=@();runtime_revision=0;runtime_learning=[ordered]@{}}|ConvertTo-Json -Depth 20|Set-Content $bb -Encoding utf8;$bs=Join-Path $tmp 'boot.ps1';$rr=Join-Path $tmp 'boot.json';$fns=@('Get-BootstrapLearningSeq','Sync-BootstrapEventToCanonicalBase','Write-BootstrapLearningEvent')|%{Get-Fn $a18 $_};$head="param([string]`$Root,[string]`$ResultPath)`n`$ErrorActionPreference='Stop'`nSet-StrictMode -Version Latest`n`$learningBasePath=Join-Path `$Root 'MININGSNIPER_LEARNING_BASE.json'`n`$learningStateDir=Join-Path `$Root 'PROTECTED_STATE\Learning'`n`$learningJournalPath=Join-Path `$learningStateDir 'LEARNING_EVENTS.jsonl'`n`$learningRunId='rc18_fail_fixture'`n`$Release='GPU_LANE_R065_RC18'`n";$tail="Write-BootstrapLearningEvent 'RUN_START' 'RUN' 'STARTED' 'fixture' 'FIXTURE' 'start' @{}|Out-Null`nWrite-BootstrapLearningEvent 'STEP_START' 'LEARNING_BOOTSTRAP' 'START' 'fixture' 'STEP_ENTER' 'enter' @{}|Out-Null`nWrite-BootstrapLearningEvent 'STEP_FAIL' 'LEARNING_BOOTSTRAP' 'FAIL' 'fixture' 'DELIBERATE_FAIL' 'fail' @{}|Out-Null`nWrite-BootstrapLearningEvent 'RUN_FINAL_FAIL' 'RUN' 'FAIL' 'fixture' 'DELIBERATE_FAIL' 'fail' @{}|Out-Null`n`$b=Get-Content -Raw `$learningBasePath|ConvertFrom-Json`n`$mine=@(`$b.runtime_event_log|?{`$_.run_id-eq`$learningRunId})`nif(`$mine.Count-ne4){throw 'bootstrap persistence count'}`n[ordered]@{status='PASS';event_count=`$mine.Count;types=@(`$mine.event_type)}|ConvertTo-Json|Set-Content `$ResultPath -Encoding utf8`nWrite-Host 'BOOT_RC18_PASS'";Set-Content $bs ($head+($fns-join"`n")+$tail) -Encoding utf8;$o=@(& pwsh -NoProfile -File $bs -Root $br -ResultPath $rr 2>&1);if($LASTEXITCODE-ne0-or$o-notcontains'BOOT_RC18_PASS'){throw('boot fixture '+($o-join' | '))};$boot=Get-Content -Raw $rr|ConvertFrom-Json
  $stage='DUTY';$ds=Join-Path $tmp 'duty.ps1';$dr=Join-Path $tmp 'duty.json';Set-Content $ds $p18['DutyFixturePayload'] -Encoding utf8;$o=@(& pwsh -NoProfile -File $ds -ResultPath $dr 2>&1);if($LASTEXITCODE-ne0-or$o-notcontains'DUTY_BEHAVIOR_EXACT_SELFTEST_PASS'){throw('duty '+($o-join' | '))};$d=Get-Content -Raw $dr|ConvertFrom-Json;if([int]$d.repaired_schedule_active_ms.'0.1'-ne200-or[int]$d.repaired_schedule_active_ms.'0.25'-ne500-or[int]$d.repaired_schedule_active_ms.'0.4'-ne800){throw'duty schedule'}
  $stage='HASHRATE';$t=$null;$e=$null;$sa=[Management.Automation.Language.Parser]::ParseInput($p18['SupervisorPayload'],[ref]$t,[ref]$e);$hs=Join-Path $tmp 'hash.ps1';$ht=(Get-Fn $sa 'Parse-LolHashrateLine')+"`n"+(Get-Fn $sa 'Convert-LolApiHashrateMhs')+"`n`n`$api=[pscustomobject]@{ok=`$true;data=[pscustomobject]@{Algorithms=@([pscustomobject]@{Algorithm='Etchash';Performance_Unit='Mh/s';Total_Performance=12.352733907856239})}}`n`$a=Convert-LolApiHashrateMhs `$api`n`$l=Parse-LolHashrateLine 'Average speed (5s): 17.89 Mh/s'`nif([Math]::Abs([double]`$a-12.352733907856239)-gt.000001-or[Math]::Abs([double]`$l-17.89)-gt.000001){throw 'hash fixture'}`nWrite-Host 'HASH_RC18_PASS'";Set-Content $hs $ht -Encoding utf8;$o=@(& pwsh -NoProfile -File $hs 2>&1);if($LASTEXITCODE-ne0-or$o-notcontains'HASH_RC18_PASS'){throw('hash '+($o-join' | '))}
  $stage='KNOWN_FAILURE_CLOSURE';foreach($bad in @('Get-LolHashrateFromLog','duty_weighted_util_proxy_pct','duty_weighted_power_proxy_w')){if($p18['SupervisorPayload'].Contains($bad)){throw('retired '+$bad)}};if($p18['SupervisorPayload']-notmatch'\$script:DutyController'){throw'DutyController scope missing'}
  $stage='SUCCESS';[ordered]@{schema='miningsniper-rc18-prechat-validation/v1';status='PASS';powershell=$PSVersionTable.PSVersion.ToString();platform=[Environment]::OSVersion.Platform.ToString();rc17_baseline_validation='PASS';rc17_sha256=(Get-FileHash $Rc17Path -Algorithm SHA256).Hash.ToLowerInvariant();rc18_sha256=(Get-FileHash $Rc18Path -Algorithm SHA256).Hash.ToLowerInvariant();rc18_bytes=(Get-Item $Rc18Path).Length;main_parse='PASS';payload_parse=$parse;payload_identity_normalized_parity_to_rc17=$parity;cpu_hard_dependency_absent=$true;main_flow=$flow;module_export_boundary='PASS';launcher_private_module_calls=0;bootstrap_failure_base_persistence=$boot;duty_status=[string]$d.status;duty_new=$d.repaired_schedule_active_ms;hashrate_api_mhs=12.352733907856239;hashrate_log_mhs=17.89;known_failure_signature_closure='PASS';user_host_touched=$false}|ConvertTo-Json -Depth 30|Set-Content $ResultPath -Encoding utf8;Write-Host 'MININGSNIPER_RC18_PRECHAT_PASS'
 }finally{Remove-Module MiningSniper.Learning -Force -ErrorAction SilentlyContinue;Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue}
}catch{FailReceipt $_.Exception.Message $_;throw}
